### PR TITLE
Finished mock screen overview with functional filtering on tags

### PR DESCRIPTION
**Pull request by john-ghatas**
Added the dev script, only used for development locally. Created a NavBar @MauritsioRK and added a filtering column on the left of the page next to the general table.

### CODE REVIEW

**Comment by john-ghatas** [comment]
Saw the linter tests failing, adding in a prettier configuration to remedy this.

**Review by mvegter — CHANGES_REQUESTED** [review]
- Remove any merge commits and rebase on master
- Changes related to the dev script are for the dev script pull requst, not this one so please remove/drop them
- I would expect mock data in the back-end not front-end
- Missing front end tests
- And as already seen, fix the linting issues

**Comment by john-ghatas** [comment]
I set up the prettier config. The linter does not recognize es6 as it shows an 'Unexpected token error' on an es6 arrow method 
image
And the same error on a valid method here:
image

EDIT: The rest of the linting errors are remedied

**Review by mvegter — CHANGES_REQUESTED** [review]
- Fix commit messages https://www.conventionalcommits.org/en/v1.0.0/
- Don't add prettier, we already have ESLint integration (thus run `npm run lint:fix`)

Edit:
- Fixup those linting commits, no need for seperate commits
- Also missing license headers

**Comment by john-ghatas** [comment]
As for the API way of getting data, that is currently not possible. I have submitted an issue about this, so for the time being it's probably best to keep it this way.

**Comment by mvegter** [comment]
@john-ghatas you can specify the full url or relative, so it is possible. Also please fix your git history.

**Review by noxi333 — CHANGES_REQUESTED** [review]
Please look at your commit tree. As this is part of our documentation this should be clear and easy to understand.

**Pull request closed without merging**
